languageCode: en-us
baseURL: "https://alpertaskiran.github.io/"
title: Another Tech Blog
paginate: 5
theme: PaperMod

minify:
    disableXML: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Alper"
    author: Theme PaperMod

    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: true

    homeInfoParams:
        Title: "Welcome to Alper's Blog"
        Content: >
            Hi, this is Alper. I'm documenting my learnings and findings in this blog. 
    socialIcons:
        - name: github
          url: "https://github.com/alpertaskiran"

    assets:
        disableHLJS: true
        
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: infographics
      name: Infographics
      url: /infographics/
      weight: 3

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true