languageCode: en-us
baseURL: "https://alpertaskiran.github.io/"
title: Another Tech Blog
paginate: 5
theme: PaperMod

minify:
    disableXML: true
enableEmoji: true
pygmentsUseClasses: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Alper"
    author: Theme PaperMod

    defaultTheme: auto
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    hideMeta: true
    hideFooter: true

    homeInfoParams:
        Title: "Welcome to Alper's Blog"
        Content: >
            Hi, this is Alper. I'm documenting my learnings and findings in this blog. 
    socialIcons:
        - name: github
          url: "https://github.com/alpertaskiran"
        - name: linkedin
          url: https://www.linkedin.com/in/alper-taskiran-52588a1b9/

    assets:
        disableHLJS: true

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
        
menu:
  main:
    - identifier: post
      name: Posts
      url: /
      weight: 1 
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 2
    - name: Tags
      url: tags/
      weight: 3
    - identifier: Search
      name: Search
      url : /search/
      weight : 4

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: true
        style: monokai

privacy:
    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
